### ISSUE TITLE
404 File not found error

### ISSUE THREAD

**Issue by vikasj** [makenew/jekyll-site#1]
I followed the instructions and pushed to my repo https://github.com/vikasj/vikas.
However, when I go to http://vikasj.github.io/vikas/

"The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file."

Am I doing something wrong?

**Comment by razor-x** [comment]
@vikasj For this project, I intentionally didn't make any assumptions on deployment. When you run `rake`, the "production ready" version of the site is built to the `dist` directory. For a project site hosted with GitHub pages, **the contents of `dist` is what needs to be on the `gh-pages` branch.**

Putting the unbuilt source on the `gh-pages` branch won't work, and the 404 error is simply because there is no `index.html` file at the root.

You can build the site locally and manually update the `gh-pages` branch, but I recommend an automated tool. Here are some I've used:
- Ruby: https://github.com/jirutka/rake-jekyll
- Gulp: https://www.npmjs.com/package/gulp-gh-pages

You can use these to deploy from your workstation after building the site, or setup Travis or some other CI to deploy for you.

**Example** I'm using the gulp plugin on a few of my projects. You can find a working example here: https://github.com/evansosenko/evansosenko.github.io/tree/wip-new

All you need is a few more npm packages, I'm using `git-rev-sync`, `gulp`, `gulp-cli`, `gulp-load-plugins`, `gulp-gh-pages`, and a gulpfile like

``` js
'use strict'

const gitRevSync = require('git-rev-sync')
const gulp = require('gulp')
const $ = require('gulp-load-plugins')()

const pkg = require('./package.json')

gulp.task('deploy', () => {
  return gulp.src('dist/**/*')
    .pipe($.ghPages({
      branch: process.env.DEPLOY_BRANCH || 'gh-pages',
      remoteUrl: `git@github.com:${pkg.repository}.git`,
      message: `Deploy ${gitRevSync.short()} from v${pkg.version}`
    }))
})
```

Add `"deploy": "gulp deploy"` to the list of npm scripts, and then you can deploy with `npm run deploy`.

If you want Travis to deploy it for you, you need to add to `.travis.yml`

```
after_success:
  - ./.travis/deploy.sh
```

and then add a deploy script and a deploy key: https://github.com/evansosenko/evansosenko.github.io/tree/wip-new/.travis
The [rake-jekyll documentation has more details on setting up a deploy key with Travis.](https://github.com/jirutka/rake-jekyll#b-use-ssh-deploy-key)

Side note: I recommending always using the https url, as you get this automatically with github pages.

**Comment by razor-x** [comment]
Actually, a better example of adding deployment is on the demo site branch: https://github.com/makenew/jekyll-site/tree/demo

Same idea, but less of my own customization to confuse the issue.

**Comment by vikasj** [comment]
Wow thanks! This makes a lot more sense now :+1:

**Comment by saman2ny** [comment]
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

**Comment by saman2ny** [comment]
help me ;
